"""empty message

Revision ID: 1405d1d25677
Revises: de77beb7eece
Create Date: 2017-04-08 17:31:32.830848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1405d1d25677'
down_revision = 'de77beb7eece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zip_code', sa.Integer(), nullable=True))
    op.drop_column('users', 'zip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zip', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('users', 'zip_code')
    # ### end Alembic commands ###
