"""empty message

Revision ID: 1eceb3f05086
Revises: ff39c94a1d6a
Create Date: 2017-04-21 16:21:09.280566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eceb3f05086'
down_revision = 'ff39c94a1d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_places', sa.Column('added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_places', 'added')
    # ### end Alembic commands ###
