"""empty message

Revision ID: 32e2320f0b41
Revises: 1eceb3f05086
Create Date: 2017-04-22 12:21:20.498333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e2320f0b41'
down_revision = '1eceb3f05086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('validated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'validated')
    # ### end Alembic commands ###
