"""empty message

Revision ID: 89b0f7d2a36b
Revises: 1405d1d25677
Create Date: 2017-04-08 18:18:42.413267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b0f7d2a36b'
down_revision = '1405d1d25677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('local', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'local')
    # ### end Alembic commands ###
